# This file can be used to create an environment with specific dependencies by running
#
# $conda env create -f environment.yml
#
# in the Anaconda Prompt

# Name of the environment
name: Qlunc_Env
# Dependencies we want to install
dependencies:
  - matplotlib==3.2.1
  - numpy==1.18.5 
  - pandas==1.2.1
  - pyyaml==5.4.1
  - scipy==1.6.0
  - sympy==1.7.1
  - xarray==0.15.1
  - spyder==4.2.1
  - python==3.7.9
  - notebook
  - jupyterlab
  - netcdf4==1.5.3
